version: '3.1'

services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"

  db:
    image: mysql
    volumes:
      - wptut:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password # default USER is root

  wordpress:
    build: ./wordpress
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - 80:80

volumes:
  wptut:
